---

- hosts: "localhost"
  gather_facts: true
  vars:
    # we should always use python3
    ansible_python_interpreter: /usr/bin/python3
    volume: "ansible-vol1"
    #state: "create"
    initiator_group: "ig-alokcentos1"
    chap_user: "alok"

  tasks:
    - name: Load Storage System Vars
      include_vars: 'properties/storage_system_properties.yml'
      tags:
        - create_acr
        - delete_acr

    # if state is create, then create acl for given volume ,fails if it exist or cannot create
    # if state is present, then create acl if not present ,else success
    - name: Create ACR for volume
      hpe_nimble_acr:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        volume: "{{ansible_default_ipv4['address']}}-{{ volume }}"
        initiator_group: "{{ansible_default_ipv4['address']}}-{{ initiator_group }}"
        # chap_user: "{{ chap_user }}"
        state: "{{ state | default('present') }}" # fail if exist
      tags:
        - create_acr

    # delete the acl for a given volume name
    - name: Delete ACR for volume
      hpe_nimble_acr:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        volume: "{{ansible_default_ipv4['address']}}-{{ volume }}"
        state: "absent" # fail if volume does not exist
      tags:
        - delete_acr