namespace: "hpe"
name: "nimble"
version: "1.0.0"
authors:
    - Hpe Nimble Storage Ansible Team (@ranjanal) <hpe_nimble-ansible-team@nimblestorage.com>
    - Alok Ranjan <alok.ranjan2@hpe.com>"
license: "Apache License, Version 2.0 or later"
readme: README.md
description: Manage HpeNimble Storage Array
repository: https://github.com/hpe-storage/nimble-ansible-modules
tags:
    - storage