namespace: hpe
name: nimble
version: 1.0.1
authors:
  - HPE Nimble Storage <nimble-dcs-storage-automation-eng@hpe.com>
license: Apache-2.0
readme: README.md
description: HPE Nimble Storage Content Collection for Ansible
repository: https://github.com/hpe-storage/nimble-ansible-modules
documentation: https://hpe-storage.github.io/nimble-ansible-modules
tags:
  - storage
homepage: http://hpe.com/storage/nimble
issues: https://github.com/hpe-storage/nimble-ansible-modules/issues
